events {}

http {
    types {
        text/css css;
        text/html html;
        application/javascript js;
        image/jpeg jpg jpeg;
        image/png png;
        image/gif gif;
        image/svg svg;
    }

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}